Fixing website typos
bdxio/bdxio.site pull request #285
Opened 2023-04-25 10:22 UTC by fcamblor

2023-04-25 10:27 UTC, antoinechassagne approved these changes
Merci pour la contrib ! 👍 
Par contre, la branche de départ devrait être `main`

2023-04-25 10:34 UTC, antoinechassagne requested changes
Merci pour la contrib ! 
Cependant, il faudrait partir de la branche `main`

2023-04-25 11:06 UTC, fcamblor commented
Il me semble que la branche `main` ne reflète pas l'état actuel du website (il y a certains contenus/typos que je vois aujourd'hui sur le site et qui ne sont plus dans `main`)

=> C'est la raison pour laquelle je suis parti de `2022`, qui me semblait assez proche de ce qui était déployé

2023-04-26 07:43 UTC, antoinechassagne commented
Je comprends la confusion, certains contenus ne sont plus en dur, c’est pour ça que vous ne les trouviez plus sur `main`.
Merci pour vos retours, nous les avons traiter dans la dernière mise à jour :) 

Par conséquent je clôture cette PR

2023-04-26 07:43 UTC, closed without merging